FROM alpine:latest

RUN apk add --no-cache curl jq

# Create a non-root user and group
RUN addgroup -S tester && adduser -S tester -G tester

WORKDIR /home/tester/app

# Copy the script and give ownership to the non-root user
COPY --chown=tester:tester test/test_endpoints.sh .

RUN chmod +x test_endpoints.sh

# Switch to the non-root user
USER tester

CMD ["/bin/sh", "./test_endpoints.sh"]
