module.exports = [
  {
    files: ["*.js"],
    languageOptions: {
      ecmaVersion: 2021,
      sourceType: "commonjs",
      globals: {
        console: "readonly",
        module: "readonly",
        process: "readonly",
        require: "readonly",
        window: "readonly",
      },
    },
    rules: {
      "consistent-return": "error",
      "default-case-last": "error",
      "array-callback-return": "error",
      curly: ["error", "all"],
      "dot-notation": "error",
      eqeqeq: ["error", "always"],
      "guard-for-in": "error",
      "no-constructor-return": "error",
      "no-duplicate-imports": "error",
      "no-else-return": ["error", { allowElseIf: false }],
      "no-implied-eval": "error",
      "no-new-wrappers": "error",
      "no-lonely-if": "error",
      "no-multi-assign": "error",
      "no-param-reassign": "error",
      "no-promise-executor-return": "error",
      "no-self-compare": "error",
      "no-shadow": "error",
      "no-throw-literal": "error",
      "no-template-curly-in-string": "error",
      "no-unneeded-ternary": "error",
      "no-unreachable-loop": "error",
      "no-useless-catch": "error",
      "no-useless-return": "error",
      "no-warning-comments": ["error", { terms: ["todo", "fixme", "xxx"], location: "start" }],
      "object-shorthand": ["error", "always"],
      "operator-assignment": ["error", "always"],
      "prefer-exponentiation-operator": "error",
      semi: ["error", "always"],
      quotes: ["error", "double"],
      "no-unused-vars": ["error", { args: "after-used", caughtErrors: "all" }],
      "no-useless-concat": "error",
      "no-var": "error",
      "no-console": "off",
      "no-undef": "error",
      "prefer-const": "error",
      "prefer-object-has-own": "error",
      "prefer-object-spread": "error",
      "prefer-regex-literals": "error",
      "prefer-template": "error",
      "require-await": "error",
      radix: "error",
      yoda: ["error", "never"],
    },
  },
  {
    files: ["*.mjs"],
    languageOptions: {
      ecmaVersion: 2021,
      sourceType: "module",
      globals: {
        console: "readonly",
        process: "readonly",
      },
    },
    rules: {
      "consistent-return": "error",
      "default-case-last": "error",
      "array-callback-return": "error",
      curly: ["error", "all"],
      "dot-notation": "error",
      eqeqeq: ["error", "always"],
      "guard-for-in": "error",
      "no-constructor-return": "error",
      "no-duplicate-imports": "error",
      "no-else-return": ["error", { allowElseIf: false }],
      "no-implied-eval": "error",
      "no-new-wrappers": "error",
      "no-lonely-if": "error",
      "no-multi-assign": "error",
      "no-param-reassign": "error",
      "no-promise-executor-return": "error",
      "no-self-compare": "error",
      "no-shadow": "error",
      "no-throw-literal": "error",
      "no-template-curly-in-string": "error",
      "no-unneeded-ternary": "error",
      "no-unreachable-loop": "error",
      "no-useless-catch": "error",
      "no-useless-return": "error",
      "no-warning-comments": ["error", { terms: ["todo", "fixme", "xxx"], location: "start" }],
      "object-shorthand": ["error", "always"],
      "operator-assignment": ["error", "always"],
      "prefer-exponentiation-operator": "error",
      semi: ["error", "always"],
      quotes: ["error", "double"],
      "no-unused-vars": ["error", { args: "after-used", caughtErrors: "all" }],
      "no-useless-concat": "error",
      "no-var": "error",
      "no-console": "off",
      "no-undef": "error",
      "prefer-const": "error",
      "prefer-object-has-own": "error",
      "prefer-object-spread": "error",
      "prefer-regex-literals": "error",
      "prefer-template": "error",
      "require-await": "error",
      radix: "error",
      yoda: ["error", "never"],
    },
  },
];
