version: 2
multi-ecosystem-groups:
  test-playwright:
    schedule:
      interval: "weekly"

updates:
  # Monitor Docker dependencies
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
  - package-ecosystem: "docker"
    directory: "/test"
    patterns:
      - "mcr.microsoft.com/playwright"
    multi-ecosystem-group: "test-playwright"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
  - package-ecosystem: "docker"
    directory: "/test"
    ignore:
      - dependency-name: "mcr.microsoft.com/playwright"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  # Monitor Python dependencies
  - package-ecosystem: "pip"
    directory: "/web"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      filesystems:
        patterns:
          - "fsspec"
          - "gcsfs"
          - "s3fs"
  - package-ecosystem: "pip"
    directory: "/test"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  # Monitor Node.js quality tooling
  - package-ecosystem: "npm"
    directory: "/test"
    patterns:
      - "playwright-core"
    multi-ecosystem-group: "test-playwright"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
  - package-ecosystem: "npm"
    directory: "/test"
    ignore:
      - dependency-name: "playwright-core"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  # Monitor GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
